---
- name: Créer le dossier de destination
  file:
    path: /var/www/html/
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraire WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    owner: www-data
    group: www-data


- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraire WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Changer les permissions du dossier WordPress
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes

- name: Créer une base de données MySQL pour WordPress
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Créer un utilisateur MySQL pour WordPress
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: localhost
    state: present

- name: Redémarrer Apache
  service:
    name: apache2
    state: restarted
